### PR TITLE
Take maxiconsize into account in menus

### PR DESCRIPTION
**Pull request by schutm**

### CODE REVIEW

**Comment by klugier** [comment]
Hell @schutm and thanks for your contribution. Can you add screenshot to your PR to see the difference between previously and with your fix? Thanks in advanced!

**Comment by schutm** [comment]
After this patch, with the rescale to the default maxiconsize 16x16:
image

Before this patch, without the rescale to the maxiconsize:
image

BTW. My icons are 24x24

**Comment by mirek-fidler** [comment]
- fix does not work well in Win10 / UHD mode
- while MaxIconSize will benefit from fixing, current default behaviour is to just scale the menu item, this is how putting large icon looks (and is expected to look) in Win10

obrazek

so what your screenshot shows is clearly a bug. Can you please share simple testing code and information about host platform?

**Comment by schutm** [comment]
```
#include <CtrlLib/CtrlLib.h>

using namespace Upp;

struct App : public TopWindow {
	MultiButton clickMe;
	Image icon;

	typedef App CLASSNAME;

	App()
	{
		// The icon should show 3 horizontal lines
		ImageDraw im(48, 48);
		im.DrawRect(0, 0, 48, 48, SColorMenu());
		im.DrawLine(Point(0, 0), Point(47, 47));
		im.DrawLine(Point(47, 0), Point(0, 47));
		im.DrawLine(Point(0, 5), Point(47, 5));
		im.DrawLine(Point(0, 27), Point(47, 27));
		im.DrawLine(Point(0, 42), Point(47, 42));
		icon = im;

		Add(clickMe.HCenterPos(200).VCenterPos(60));
		clickMe.AddButton().WhenClick << [&] {
			MenuBar bar;
			bar.Add("Item 1", icon, [&] { Exclamation("Item 1 invoked"); });
			bar.Add("Item 2", icon, [&] { Exclamation("Item 2 invoked"); });
			bar.Add("Item 3", icon, [&] { Exclamation("Item 3 invoked"); });

			Point menuPosition = clickMe.GetPushScreenRect().BottomRight();
			Size menuSize = bar.GetSize(); // Size(bar.GetWidth(), bar.GetHeight());
			MenuFrame().FrameAddSize(menuSize);
	
			bar.Execute(Point(menuPosition - Point(menuSize.cx, 0)));
		};
	}
};

GUI_APP_MAIN { App().Run(); }
```
Shows:
image

Expected:
image

**Comment by mirek-fidler** [comment]
Should be now fixed, however to achieve "Expected:", you need to add
bar.MaxIconSize(DPI(16)).

**Comment by klugier** [comment]
@schutm can you confirm that this issue has been resolved? If, yes please close the PR. Thanks in advanced!

**Pull request closed without merging**
