### PR TITLE
Horizontal Mouse wheel support and Topic++ group export fix

### PR DESCRIPTION
**Pull request by User0755**
- Adds feature Horizontal Mouse Wheel support in CtrlCore for POSIX and Win32.
- Fixes touch/pen detection for Win32 to allow touch screen gestures to pass through as normal mouse ops.
- Fixes cross linking of files in Topic++ group export result files (PDFs and HTMLs).

### CODE REVIEW

**Comment by klugier** [comment]
Hello Tom,

Thanks for creating this PR! Optimally it should be divided into three/four separate PR's (on your fork you can have multiple branches):
- dedicated to horizontal mouse wheel support
- dedicated to touch screen gestures
- dedicated to topic++ improvemenets
- dedicated to zip64 support

Right now we have a problem everything or nothing. With separation of PR's some of things might be merged sooner than later. So, please reconsider dividing your PR's. Of course Mirek will have last word, but from my point of view it is the best approach. I added Mirek to the review.

Klugier

**Comment by User0755** [comment]
Hi Klugier,

I proceeded while learning from the github docs and ended up in this unfavorable situation. When I discovered the problem of them all being bundled together, it was too late (or early if you look at the clock) to figure out how to fix it.

Anyway, I will try to learn about managing branches and get better results next time. (In any case, I have to say that this seems like a lot of work to get a few files transferred.)

Thanks for your attention and guidance.

Best regards,

Tom

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by klugier** [comment]
Hello Tom,

Sure. Thanks for reflection! I think Mirek will be able to modify your patches to integrate them with master branch.

Klugier

**Comment by User0755** [comment]
Hi, I just completed splitting them to separate branches. Should I now create PRs for each of them and cancel the original multi feature PR?

Tom

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by klugier** [comment]
Hello Tom,

If you can, please do that. Separate PR's with dedicated changes is optimal approach.

Klugier

**Comment by User0755** [comment]
Hi Klugier,

I think this PR is now redundant. All four categories here are now covered in separate PRs pointing to specific branches.

Tom

**Pull request closed without merging**
