### PR TITLE
UMK as pure console application

### PR DESCRIPTION
**Pull request by klugier**
In the current version of UMK there is a depenendency to Draw and plugin/png package. It is not perfect since UMK is designed to be pure console appliccation. My PR is adressing this issue by modifying ide/Builders package dependnecies.

Before the PR UMK dependencies looks like this:
```
~/upp $ ldd umk
        linux-vdso.so.1 (0x00007ffff0819000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007ff281f18000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007ff281efe000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007ff281b31000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007ff281eae000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007ff2819ee000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007ff2819c3000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007ff281998000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007ff281985000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff281ea7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007ff281ea2000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007ff281980000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ff281600000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007ff281898000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ff281878000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff281419000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007ff28132e000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007ff28186a000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007ff281865000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007ff28185d000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff281f88000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007ff28183b000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007ff2811f1000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007ff2811ce000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007ff281133000)
```

After, it is:
```
ldd umk 
        linux-vdso.so.1 (0x00007f7da63b0000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f7da6362000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f7da6348000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7da5a00000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f7da5d18000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7da6328000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f7da5819000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7da63b2000)
```

* This change might required makefile regeneration after merge.

### CODE REVIEW

**Comment by mirek-fidler** [comment]
There is one problem with this (and the reason why Draw was brought in). Check Builders/Cocoa.cpp.

Now I agree that we are postponing MacOS X, but it would be worth not to break this one anyway.

**Comment by klugier** [comment]
OK, now I see. Thanks for letting me know...

**Comment by mirek-fidler** [comment]
Uhm, I did not mean this is wrong idea. Just please instead of removing uses completele, change the condition to OSX and then test with mac (that is the time consuming part...)

**Comment by klugier** [comment]
@mirek-fidler I fix it as you suggested. Now, the UI dependency is for OSX only and UMK for Linux is pure console application.

Tested on macOS. (14 packages build on macOS vs 12 on Linux)

**Pull request merged**
